[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ee4309-vitdet"
version = "0.1.0"
description = "EE4309 ViTDet Project"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["src"]
